<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.5.0" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.8.0" />
    <PackageReference Include="Google.Apis.Admin.Directory.directory_v1" Version="1.74.0.4128" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Teams.AI.Models.OpenAI" Version="2.0.6" />
    <PackageReference Include="OpenTelemetry" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.15.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="8.1.1" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
  <PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LightCap.InvestmentApi.Application\LightCap.InvestmentApi.Application.csproj" />
    <ProjectReference Include="..\LightCap.InvestmentApi.Infrastructure\LightCap.InvestmentApi.Infrastructure.csproj" />
    <ProjectReference Include="..\LightCap.InvestmentApi.Persistence\LightCap.InvestmentApi.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ApiMessages\" />
    <Folder Include="Filters\" />
  </ItemGroup>

</Project>
